# check it first with http://yaml-online-parser.appspot.com/ if valid!
site_config:
  title: anergel
  keywords: anergel
  description: anergel

development:
  MONGODB_URI_DEV: mongodb://localhost:27017

test:
  MONGODB_URI_TEST: mongodb://localhost:27017

production:
  MONGODB_URI: mongodb://localhost:27017




